import { useEffect, useMemo, useState } from "react";
import type { SlicerEntry } from "../store/slicers";
import "./InsertSlicerDialog.css";

interface AvailableTable {
  /** Workbook-unique table name (from `_tables[].name`). */
  name: string;
  /** Sheet id hosting the table — used by the caller to attach the slicer. */
  sheetId: string;
  /** Column header names; the user picks the slicer's "field" from this list. */
  columns: string[];
}

interface Props {
  /** Tables a slicer can target — flattened from the workbook's `_tables`. */
  availableTables: AvailableTable[];
  /**
   * Called when the user clicks "作成". `sheetId` is the host sheet of the
   * target table — the slicer is stored there (workbook-wide `_slicers` would
   * have made the filter pipeline harder to reason about).
   */
  onApply: (entry: SlicerEntry, sheetId: string) => void;
  onClose: () => void;
}

export default function InsertSlicerDialog({
  availableTables,
  onApply,
  onClose,
}: Props) {
  // Default to the first available table — the dialog is opened from the
  // Insert menu, so the user hasn't necessarily clicked into a specific
  // table beforehand. Empty list is handled in the body.
  const [tableName, setTableName] = useState<string>(() =>
    availableTables[0]?.name ?? "",
  );
  const [field, setField] = useState<string>(() =>
    availableTables[0]?.columns[0] ?? "",
  );
  const [error, setError] = useState<string | null>(null);

  // Look up the selected table so we can populate the field dropdown. Keep
  // this memoized — the available-tables list comes from the snapshot and
  // re-renders frequently as the user types into other dialogs.
  const selectedTable = useMemo(
    () => availableTables.find((t) => t.name === tableName) ?? null,
    [availableTables, tableName],
  );

  // When the user switches tables, reset the field to the first column of
  // the new table. Otherwise a stale field name from the previous table can
  // sneak through validation (it might exist on the new table, but the user
  // likely didn't intend to keep it).
  useEffect(() => {
    if (!selectedTable) {
      setField("");
      return;
    }
    if (!selectedTable.columns.includes(field)) {
      setField(selectedTable.columns[0] ?? "");
    }
  }, [selectedTable, field]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        onClose();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const submit = () => {
    if (!selectedTable) {
      setError("対象テーブルを選択してください");
      return;
    }
    const fieldTrim = field.trim();
    if (!fieldTrim) {
      setError("フィールドを選択してください");
      return;
    }
    if (!selectedTable.columns.includes(fieldTrim)) {
      setError("選択したフィールドはテーブルに存在しません");
      return;
    }
    setError(null);
    // Name is auto-generated by the caller (it has workbook-wide visibility
    // into existing slicer names via `generateSlicerName`). We hand back an
    // entry with an empty name and let the caller fill it in — keeps the
    // dialog ignorant of workbook state it doesn't need.
    const entry: SlicerEntry = {
      name: "",
      targetTable: selectedTable.name,
      field: fieldTrim,
      selectedValues: [],
    };
    onApply(entry, selectedTable.sheetId);
    onClose();
  };

  const empty = availableTables.length === 0;

  return (
    <div className="isd-backdrop" onClick={onClose}>
      <div
        className="isd-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="isd-title"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="isd-header">
          <h2 id="isd-title" className="isd-title">スライサーの挿入</h2>
          <button type="button" className="isd-close" onClick={onClose} aria-label="閉じる">
            ×
          </button>
        </header>
        <div className="isd-body">
          {empty ? (
            <p className="isd-empty">
              このブックにはテーブルがありません。先に [挿入] → [テーブル] で
              スライサーの対象テーブルを作成してください。
            </p>
          ) : (
            <>
              <label className="isd-field">
                <span className="isd-field-label">対象テーブル</span>
                <select
                  className="isd-select"
                  value={tableName}
                  onChange={(e) => setTableName(e.target.value)}
                  autoFocus
                >
                  {availableTables.map((t) => (
                    <option key={`${t.sheetId}:${t.name}`} value={t.name}>
                      {t.name}
                    </option>
                  ))}
                </select>
              </label>
              <label className="isd-field">
                <span className="isd-field-label">フィールド (列)</span>
                <select
                  className="isd-select"
                  value={field}
                  onChange={(e) => setField(e.target.value)}
                  disabled={!selectedTable || selectedTable.columns.length === 0}
                >
                  {selectedTable?.columns.map((col) => (
                    <option key={col} value={col}>
                      {col}
                    </option>
                  ))}
                </select>
              </label>
              {error && <p className="isd-error">{error}</p>}
            </>
          )}
        </div>
        <footer className="isd-footer">
          <p className="isd-hint">
            選択したフィールドの値ごとにボタンを表示します。ボタンをクリックして
            対象テーブルの行をフィルタできます (Excel のスライサー相当)。
          </p>
          <div className="isd-footer-actions">
            <button type="button" className="isd-btn" onClick={onClose}>
              キャンセル
            </button>
            <button
              type="button"
              className="isd-btn isd-btn--primary"
              onClick={submit}
              disabled={empty}
            >
              作成
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
