// #179 (area D): Japanese `abstract` strings for Univer's formula functions.
//
// HISTORY: at Univer 0.5.x, Coco had to serve JA UI from the EN_US locale slot
// because Univer didn't ship `LocaleType.JA_JP`. Every function's `abstract`
// in the formula helper / autocomplete was English, so this file shipped JA
// translations to fill the gap.
//
// CURRENT (post-PR #218, Univer 0.12+): Univer ships native `LocaleType.JA_JP`
// and `@univerjs/sheets-formula-ui` includes JA `abstract` text for ALL 245
// functions in this map (and many more). The overlay still applies via the
// last-wins `mergeLocales` in cocoUniverLocale.ts, so **Coco's strings now
// override Univer's native JA** (shorter / more literal vs. Univer's longer
// Microsoft-style phrasing). This is a translation-quality preference, not a
// gap fill. A future cleanup may drop this file entirely if the team decides
// Univer's native JA is fine; for now it stays so the formula picker keeps
// the wording users are familiar with.
//
// To add a function, append `NAME: { abstract: "..." }`. Names must match
// Univer's `formula.functionList` keys exactly (Excel upper-case).

export const FUNCTION_LIST_JA_ABSTRACT: Readonly<Record<string, string>> = {
  // ---------- Math & Trig ----------
  ABS: "数値の絶対値を返します",
  ACOS: "数値の逆余弦を返します",
  ASIN: "数値の逆正弦を返します",
  ATAN: "数値の逆正接を返します",
  ATAN2: "X 座標と Y 座標から逆正接を返します",
  CEILING: "指定した基準値の倍数に切り上げます",
  CEILING_MATH: "数値を最も近い整数または基準値の倍数に切り上げます",
  COMBIN: "組み合わせの数を返します",
  COS: "数値の余弦を返します",
  DEGREES: "ラジアンを度に変換します",
  EVEN: "数値を最も近い偶数に切り上げます",
  EXP: "e を底とするべき乗を返します",
  FACT: "数値の階乗を返します",
  FLOOR: "指定した基準値の倍数に切り捨てます",
  FLOOR_MATH: "数値を最も近い整数または基準値の倍数に切り捨てます",
  GCD: "最大公約数を返します",
  INT: "数値を最も近い整数に切り捨てます",
  LCM: "最小公倍数を返します",
  LN: "数値の自然対数を返します",
  LOG: "指定した底での対数を返します",
  LOG10: "10 を底とする対数を返します",
  MOD: "除算の剰余を返します",
  MROUND: "指定した基準値の倍数に丸めます",
  ODD: "数値を最も近い奇数に切り上げます",
  PI: "円周率 π を返します",
  POWER: "数値のべき乗を返します",
  PRODUCT: "引数の積を返します",
  QUOTIENT: "除算の商の整数部を返します",
  RADIANS: "度をラジアンに変換します",
  RAND: "0 以上 1 未満の乱数を返します",
  RANDARRAY: "乱数の配列を返します",
  RANDBETWEEN: "指定した範囲の整数の乱数を返します",
  ROMAN: "アラビア数字をローマ数字に変換します",
  ROUND: "数値を指定した桁数に四捨五入します",
  ROUNDDOWN: "数値を指定した桁数に切り捨てます",
  ROUNDUP: "数値を指定した桁数に切り上げます",
  SEQUENCE: "連続した数値の配列を生成します",
  SIGN: "数値の符号を返します",
  SIN: "数値の正弦を返します",
  SQRT: "数値の正の平方根を返します",
  SUBTOTAL: "リストやデータベースの集計値を返します",
  SUM: "引数の合計を返します",
  SUMIF: "条件に一致するセルの合計を返します",
  SUMIFS: "複数の条件に一致するセルの合計を返します",
  SUMPRODUCT: "対応する配列要素の積の合計を返します",
  SUMSQ: "引数の平方和を返します",
  TAN: "数値の正接を返します",
  TRUNC: "数値の小数部を切り捨てて整数にします",

  // ---------- Statistical ----------
  AVEDEV: "データの平均偏差を返します",
  AVERAGE: "引数の平均値を返します",
  AVERAGEA: "数値以外を含む引数の平均値を返します",
  AVERAGEIF: "条件に一致するセルの平均値を返します",
  AVERAGEIFS: "複数の条件に一致するセルの平均値を返します",
  CORREL: "2 つのデータ範囲の相関係数を返します",
  COUNT: "範囲内の数値の個数を返します",
  COUNTA: "範囲内の空白でないセルの個数を返します",
  COUNTBLANK: "範囲内の空白セルの個数を返します",
  COUNTIF: "条件に一致するセルの個数を返します",
  COUNTIFS: "複数の条件に一致するセルの個数を返します",
  DEVSQ: "偏差の平方和を返します",
  FORECAST: "既存の値から将来の値を予測します",
  FORECAST_LINEAR: "線形回帰により将来の値を予測します",
  FREQUENCY: "頻度分布を縦方向の配列で返します",
  GEOMEAN: "引数の幾何平均を返します",
  HARMEAN: "引数の調和平均を返します",
  INTERCEPT: "回帰直線の切片を返します",
  KURT: "データの尖度を返します",
  LARGE: "データの中で k 番目に大きい値を返します",
  MAX: "引数の最大値を返します",
  MAXA: "数値以外を含む引数の最大値を返します",
  MAXIFS: "条件に一致するセルの最大値を返します",
  MEDIAN: "引数の中央値を返します",
  MIN: "引数の最小値を返します",
  MINA: "数値以外を含む引数の最小値を返します",
  MINIFS: "条件に一致するセルの最小値を返します",
  MODE_SNGL: "データの中で最も頻繁に出現する値を返します",
  MODE_MULT: "データの中で頻出する値を縦方向の配列で返します",
  PERCENTILE_INC: "範囲内のデータの k 番目の百分位数を返します",
  PERCENTILE_EXC: "0 と 1 を除く範囲で k 番目の百分位数を返します",
  PERCENTRANK_INC: "データセット内の値の順位を百分率で返します",
  PERMUT: "順列の数を返します",
  RANK_EQ: "数値の順位を返します",
  RANK_AVG: "数値の順位を返します(同順位は平均)",
  RSQ: "回帰直線の決定係数を返します",
  SKEW: "分布の歪度を返します",
  SLOPE: "回帰直線の傾きを返します",
  SMALL: "データの中で k 番目に小さい値を返します",
  STANDARDIZE: "正規化された値を返します",
  STDEV_S: "標本に基づく標準偏差を返します",
  STDEV_P: "母集団全体に基づく標準偏差を返します",
  STDEVA: "数値以外を含む標本の標準偏差を返します",
  TRIMMEAN: "データの中間項の平均を返します",
  VAR_S: "標本に基づく分散を返します",
  VAR_P: "母集団全体に基づく分散を返します",
  VARA: "数値以外を含む標本の分散を返します",

  // ---------- Lookup & Reference ----------
  ADDRESS: "行番号と列番号からセル参照を文字列で返します",
  AREAS: "参照に含まれる領域の数を返します",
  CHOOSE: "インデックスに基づいて値を選択します",
  COLUMN: "セル参照の列番号を返します",
  COLUMNS: "配列や範囲の列数を返します",
  FILTER: "条件に基づいて範囲をフィルター処理します",
  FORMULATEXT: "数式を文字列として返します",
  HLOOKUP: "範囲の先頭行を検索して値を返します",
  HYPERLINK: "ハイパーリンクを作成します",
  INDEX: "行と列の番号で参照内の値を返します",
  INDIRECT: "文字列で指定された参照を返します",
  LOOKUP: "1 行または 1 列の範囲から値を検索します",
  MATCH: "範囲内で値を検索し相対位置を返します",
  OFFSET: "基準セルからのオフセット参照を返します",
  ROW: "セル参照の行番号を返します",
  ROWS: "配列や範囲の行数を返します",
  SORT: "範囲または配列を並べ替えます",
  SORTBY: "別の範囲の値に基づいて並べ替えます",
  TRANSPOSE: "配列の行と列を入れ替えます",
  UNIQUE: "範囲または配列から一意の値を返します",
  VLOOKUP: "範囲の先頭列を検索して値を返します",
  XLOOKUP: "範囲または配列を検索して値を返します",
  XMATCH: "範囲または配列内で項目の相対位置を返します",

  // ---------- Logical ----------
  AND: "すべての引数が TRUE のとき TRUE を返します",
  FALSE: "論理値 FALSE を返します",
  IF: "条件を判定して異なる値を返します",
  IFERROR: "数式がエラーのとき指定した値を返します",
  IFNA: "数式が #N/A のとき指定した値を返します",
  IFS: "複数の条件を順に判定します",
  LAMBDA: "再利用可能なカスタム関数を作成します",
  NOT: "引数の論理値を反転します",
  OR: "いずれかの引数が TRUE のとき TRUE を返します",
  SWITCH: "値を一覧と照合して結果を返します",
  TRUE: "論理値 TRUE を返します",
  XOR: "引数の排他的論理和を返します",

  // ---------- Information ----------
  CELL: "セルの書式や位置、内容に関する情報を返します",
  ERROR_TYPE: "エラーの種類に対応する数値を返します",
  INFO: "現在の動作環境に関する情報を返します",
  ISBLANK: "値が空白セルのとき TRUE を返します",
  ISERR: "値が #N/A 以外のエラーのとき TRUE を返します",
  ISERROR: "値がエラー値のとき TRUE を返します",
  ISEVEN: "数値が偶数のとき TRUE を返します",
  ISFORMULA: "セルに数式が含まれるとき TRUE を返します",
  ISLOGICAL: "値が論理値のとき TRUE を返します",
  ISNA: "値が #N/A のとき TRUE を返します",
  ISNONTEXT: "値が文字列以外のとき TRUE を返します",
  ISNUMBER: "値が数値のとき TRUE を返します",
  ISODD: "数値が奇数のとき TRUE を返します",
  ISREF: "値がセル参照のとき TRUE を返します",
  ISTEXT: "値が文字列のとき TRUE を返します",
  N: "値を数値に変換します",
  NA: "エラー値 #N/A を返します",
  SHEET: "参照先シートのシート番号を返します",
  SHEETS: "参照に含まれるシート数を返します",
  TYPE: "値のデータ型を表す数値を返します",

  // ---------- Text ----------
  ASC: "全角文字を半角文字に変換します",
  CHAR: "文字コードに対応する文字を返します",
  CLEAN: "印刷できない文字を文字列から削除します",
  CODE: "文字列の先頭文字の文字コードを返します",
  CONCAT: "複数の範囲や文字列を連結します",
  CONCATENATE: "複数の文字列を 1 つに連結します",
  DOLLAR: "数値を通貨形式の文字列に変換します",
  EXACT: "2 つの文字列が同一か比較します",
  FIND: "文字列内で別の文字列を検索します(大文字小文字を区別)",
  FIXED: "数値を桁区切り付きの文字列に変換します",
  LEFT: "文字列の先頭から指定文字数を返します",
  LEN: "文字列の文字数を返します",
  LOWER: "文字列をすべて小文字に変換します",
  MID: "文字列の指定位置から指定文字数を返します",
  NUMBERVALUE: "文字列をロケールに依存しない数値に変換します",
  PROPER: "各単語の先頭文字を大文字に変換します",
  REPLACE: "文字列の一部を別の文字列に置き換えます",
  REPT: "文字列を指定回数繰り返します",
  RIGHT: "文字列の末尾から指定文字数を返します",
  SEARCH: "文字列内で別の文字列を検索します(大文字小文字を区別しない)",
  SUBSTITUTE: "文字列内の指定文字列を置き換えます",
  T: "値が文字列のときその文字列を返します",
  TEXT: "数値を書式設定した文字列に変換します",
  TEXTAFTER: "指定した区切り文字より後の文字列を返します",
  TEXTBEFORE: "指定した区切り文字より前の文字列を返します",
  TEXTJOIN: "区切り文字を挟んで複数の文字列を連結します",
  TEXTSPLIT: "区切り文字で文字列を分割します",
  TRIM: "文字列から余分な空白を削除します",
  UNICHAR: "コードポイントに対応する Unicode 文字を返します",
  UNICODE: "文字列の先頭文字のコードポイントを返します",
  UPPER: "文字列をすべて大文字に変換します",
  VALUE: "文字列を数値に変換します",

  // ---------- Date & Time ----------
  DATE: "年、月、日から日付を返します",
  DATEDIF: "2 つの日付の間の期間を返します",
  DATEVALUE: "日付を表す文字列をシリアル値に変換します",
  DAY: "日付から日を返します",
  DAYS: "2 つの日付の間の日数を返します",
  DAYS360: "1 年を 360 日として日数を計算します",
  EDATE: "指定した月数だけ前後の日付を返します",
  EOMONTH: "指定した月数だけ前後の月の末日を返します",
  HOUR: "時刻から時を返します",
  ISOWEEKNUM: "日付の ISO 週番号を返します",
  MINUTE: "時刻から分を返します",
  MONTH: "日付から月を返します",
  NETWORKDAYS: "2 つの日付の間の稼働日数を返します",
  NOW: "現在の日付と時刻を返します",
  SECOND: "時刻から秒を返します",
  TIME: "時、分、秒から時刻を返します",
  TIMEVALUE: "時刻を表す文字列をシリアル値に変換します",
  TODAY: "現在の日付を返します",
  WEEKDAY: "日付に対応する曜日番号を返します",
  WEEKNUM: "日付がその年の何週目かを返します",
  WORKDAY: "指定した稼働日数だけ前後の日付を返します",
  YEAR: "日付から年を返します",
  YEARFRAC: "2 つの日付の間の期間が 1 年に占める割合を返します",

  // ---------- Financial ----------
  DB: "定率法で資産の減価償却費を返します",
  DDB: "倍率逓減法で資産の減価償却費を返します",
  FV: "投資の将来価値を返します",
  IPMT: "投資期間中の指定期の利息を返します",
  IRR: "キャッシュフローの内部収益率を返します",
  NPER: "投資に必要な期間を返します",
  NPV: "定期的なキャッシュフローの正味現在価値を返します",
  PMT: "ローンの定期支払額を返します",
  PPMT: "投資期間中の指定期の元金返済額を返します",
  PV: "投資の現在価値を返します",
  RATE: "投資の利率を返します",
  SLN: "定額法で資産の減価償却費を返します",
  SYD: "級数法で資産の減価償却費を返します",
  XIRR: "不定期のキャッシュフローの内部収益率を返します",
  XNPV: "不定期のキャッシュフローの正味現在価値を返します",

  // ---------- Engineering ----------
  BIN2DEC: "2 進数を 10 進数に変換します",
  BIN2HEX: "2 進数を 16 進数に変換します",
  BIN2OCT: "2 進数を 8 進数に変換します",
  BITAND: "2 つの数値のビット単位の論理積を返します",
  BITOR: "2 つの数値のビット単位の論理和を返します",
  BITXOR: "2 つの数値のビット単位の排他的論理和を返します",
  CONVERT: "数値を別の単位系に変換します",
  DEC2BIN: "10 進数を 2 進数に変換します",
  DEC2HEX: "10 進数を 16 進数に変換します",
  DEC2OCT: "10 進数を 8 進数に変換します",
  DELTA: "2 つの数値が等しいか判定します",
  HEX2BIN: "16 進数を 2 進数に変換します",
  HEX2DEC: "16 進数を 10 進数に変換します",
  HEX2OCT: "16 進数を 8 進数に変換します",
  OCT2BIN: "8 進数を 2 進数に変換します",
  OCT2DEC: "8 進数を 10 進数に変換します",
  OCT2HEX: "8 進数を 16 進数に変換します",

  // ---------- Database ----------
  DAVERAGE: "条件に一致するデータベースの列の平均を返します",
  DCOUNT: "条件に一致するデータベースの数値セルを数えます",
  DCOUNTA: "条件に一致するデータベースの空白でないセルを数えます",
  DGET: "条件に一致するデータベースの 1 件の値を返します",
  DMAX: "条件に一致するデータベースの列の最大値を返します",
  DMIN: "条件に一致するデータベースの列の最小値を返します",
  DSUM: "条件に一致するデータベースの列の合計を返します",

  // ---------- Web ----------
  ENCODEURL: "文字列を URL エンコード形式に変換します",
};

/** Number of functions with a JA abstract — exposed for tests/diagnostics. */
export const FUNCTION_LIST_JA_COUNT = Object.keys(
  FUNCTION_LIST_JA_ABSTRACT,
).length;
